### ISSUE TITLE
Details of quality rating

### ISSUE THREAD

**Issue by ShangQingTu** [wagner-group/MarkMyWords#1]
Thanks for your great work~
As mentioned in Section 4.1:
> However, the tasks we ask it to rate are simple, and when comparing GPT4 ratings to LLama-2 average ratings over the benchmark, we found a strong correlation ($R^2$ of 0.96) giving us faith in Llama-2’s discernment.

I wonder how much GPT-4 labels are collected to calculate the correlation with Llama-2? As far as I know, [PandaLM](https://github.com/WeOpenML/PandaLM) trained thier model on  1M samples to learn the evaluation ability of GPT-3.5, only achieving 93.75%  GPT-3.5's evaluation ability and 88.28% of GPT-4's in terms of F1-score on thier test dataset.
Can provide you more details for your rating method? Thanks a lot!

**Comment by julien-piet** [comment]
Hi, thanks for your interest! 

Our rating method prompts Llama-2 to grade generations, based on the generation prompt and responses. The prompt we engineered to do this is in the `quality.py` file. Although it produces on average similar results to GPT-4, it most likely does not perform as well as GPT on more complex tasks. However, since our tasks are simple, we stick to Llama2.

The benefits of using Llama2 are that the model won't evolve in time, unlike GPT that could be updated and thus skew future results.

We are working on an update to the paper, after realizing that the Llama-2 hugging face implementation had a bug that once fixed changed the behavior of the model (https://github.com/ggerganov/llama.cpp/issues/2373). In this update we will also provide some more details about the rating strategy.

**Comment by ShangQingTu** [comment]
Thanks for your reply!
I also tested the Llama-2-7B-Chat with watermarks on some tasks and I reported the results in [WaterBench](https://arxiv.org/abs/2311.07138). If your rating strategy works well, I will try them in my experiments too.
Looking forward to your update~
